name: mani144
title: Mani144 | A blog for developers
description: This blog will mainly talk about Data Science and Godot.
tags:
  - godot
  - development
email: a.albar144@gmail.com
disqus_username: disqus_username
show_hero: true
